%script for extracting all laser trigger

%%
threshold=2e4;
laser_thre=15; %laser length threshold in millisecond
fs=20e3;
win=[-30 0]; %window to search for trigger to behavior

%%
[f,p]=uigetfile('*.dat','Select original Data file, laser trigger Nch=33');
[ftxt,ptxt]=uigetfile('*.txt','Select laser time generated by Stimu timer');

%%
data=readmulti_frank([p f],33,33,0,inf);

%%
txt=importdata([ptxt ftxt]);
all_txt=txt.textdata(2:end-1);

true_idx=find(cellfun(@(x) ~isempty(strfind(x,'True')),all_txt));
false_idx=find(cellfun(@(x) ~isempty(strfind(x,'False')),all_txt));
true_time=cellfun(@stimu_timer_StringConverter,all_txt(true_idx+1));
false_time=cellfun(@stimu_timer_StringConverter,all_txt(false_idx+1));

[all_time,ix]=sort([true_time ;false_time]);
all_idx=[true_idx>0 ; -1*(false_idx>0)];
all_idx=all_idx(ix);
%%
bhv_TF=zeros(size(data));
for idx=length(all_time):-1:1
    index_mask=(all_time(idx)+win(1))*fs:(all_time(idx)+win(2))*fs;
    index_mask(index_mask<=0)=[];
    index_mask(index_mask>length(data))=[];
    unset_idx=bhv_TF(index_mask)==0;
    bhv_TF(index_mask(unset_idx))=all_idx(idx);
end

locs=data>threshold;
locs_diff=diff([0 ;locs]);
locs_starts=find(locs_diff==1);
locs_ends=find(locs_diff==-1);
locs_length=locs_ends-locs_starts;
locs_true=bhv_TF(locs_starts)==1;
locs_false=bhv_TF(locs_starts)==-1;

len_thre=laser_thre*fs/1000;
idx_high_true=find((locs_length>len_thre)&locs_true);
idx_low_true=find((locs_length<len_thre)&locs_true);
idx_high_false=find((locs_length>len_thre)&locs_false);
idx_low_false=find((locs_length<len_thre)&locs_false);

idxs{1}=idx_high_true;attr{1}='.ths';
idxs{2}=idx_high_false;attr{2}='.fhs';
idxs{3}=idx_low_true;attr{3}='.tls';
idxs{4}=idx_low_false;attr{4}='.fls';

for c_idx=1:length(idxs)
    locs_this=zeros(length(idxs{c_idx}),1);
    events.description=cell(length(locs_this)*2,1);
    for idx=1:length(locs_this)
        locs_this(2*idx-1)=locs_starts(idxs{c_idx}(idx));
        events.description{2*idx-1}='Start';
        locs_this(2*idx)=locs_ends(idxs{c_idx}(idx));
        events.description{2*idx}='End';
    end
    events.time=locs_this/fs;
    if ispc
        system(['del "' p f(1:end-4) attr{c_idx} '.evt"']);
    else
        system(['rm ''' p f(1:end-4) attr{c_idx}  '.evt''']);
    end
    SaveEvents([p f(1:end-4) attr{c_idx}  '.evt'],events);
end
