%script for extracting all laser trigger

%%
laser_thre=15; %laser length threshold in millisecond
fs=20e3;
win=[-30 0]; %window to search for trigger to behavior
manual_offset=20;
%%
[f,p]=uigetfile('*digitalin.dat','Select intan digital input file');
cd(p);
[ftxt,ptxt]=uigetfile('*.txt','Select laser time generated by Stimu timer');
s=listdlg('PromptString',['Select laser trigger channel: ' ftxt],...
    'SelectionMode','single',...
    'ListString',arrayfun(@num2str,0:15,'uniformoutput',0));
%%
rawdata=readmulti_frank([p f],1,1,0,inf,'uint16');
bindata=dec2digits(rawdata,16);
data=bindata(:,s);

locs=data;
locs_diff=diff([0 ;locs]);
locs_starts=find(locs_diff==1);
locs_ends=find(locs_diff==-1);

%%
txt=importdata([ptxt ftxt]);
all_txt=txt.textdata(2:end-1);

true_idx=find(cellfun(@(x) ~isempty(strfind(x,'True')),all_txt));
false_idx=find(cellfun(@(x) ~isempty(strfind(x,'False')),all_txt));
true_time=cellfun(@stimu_timer_StringConverter,all_txt(true_idx+1));
false_time=cellfun(@stimu_timer_StringConverter,all_txt(false_idx+1));
time_combined=cellfun(@stimu_timer_StringConverter,all_txt(2:2:end)); %all time listed in the txt file
time_offset_start=locs_starts(end)/fs-time_combined(end)+30;
time_offset_range=time_offset_start-1000:1:time_offset_start;
total_bias=zeros(length(time_offset_range),1);
for idx=1:length(time_offset_range)
    time_this=time_combined+time_offset_range(idx);
    b=0;
    for i=1:length(time_this)
        x=time_this(i)-locs_starts/fs;
        x(find(x<0))=[];
        if(isempty(x))
            x=min(abs(time_this(i)-locs_starts/fs));
        end
        b=b+min(x);
    end
    total_bias(idx)=b;
end
[~,idx]=min(total_bias);
time_offset=time_offset_range(idx);
% time_offset=locs_starts(1)/fs-min([true_time;false_time])+manual_offset;
true_time=true_time+time_offset;
false_time=false_time+time_offset;
[all_time,ix]=sort([true_time ;false_time]);
all_idx=[true_idx>0 ; -1*(false_idx>0)];
all_idx=all_idx(ix);
%%
bhv_TF=zeros(size(data));
for idx=length(all_time):-1:1
    index_mask=round((all_time(idx)+win(1))*fs):round((all_time(idx)+win(2))*fs);
    index_mask(index_mask<=0)=[];
    index_mask(index_mask>length(data))=[];
    unset_idx=bhv_TF(index_mask)==0;
    bhv_TF(index_mask(unset_idx))=all_idx(idx);
end

locs_length=locs_ends-locs_starts;
locs_true=bhv_TF(locs_starts)==1;
locs_false=bhv_TF(locs_starts)==-1;
len_thre=laser_thre*fs/1000;
idx_high_true=find((locs_length>len_thre)&locs_true);
idx_low_true=find((locs_length<len_thre)&locs_true);
idx_high_false=find((locs_length>len_thre)&locs_false);
idx_low_false=find((locs_length<len_thre)&locs_false);

idxs{1}=idx_high_true;attr{1}='.ths';
idxs{2}=idx_high_false;attr{2}='.fhs';
idxs{3}=idx_low_true;attr{3}='.tls';
idxs{4}=idx_low_false;attr{4}='.fls';

for c_idx=1:length(idxs)
    locs_this=zeros(length(idxs{c_idx}),1);
    events.description=cell(length(locs_this)*2,1);
    for idx=1:length(locs_this)
        locs_this(2*idx-1)=locs_starts(idxs{c_idx}(idx));
        events.description{2*idx-1}='Start';
        locs_this(2*idx)=locs_ends(idxs{c_idx}(idx));
        events.description{2*idx}='End';
    end
    events.time=locs_this/fs;
    if ispc
        system(['del "' p f(1:end-4) attr{c_idx} '.evt"']);
    else
        system(['rm ''' p f(1:end-4) attr{c_idx}  '.evt''']);
    end
    SaveEvents([p f(1:end-4) attr{c_idx}  '.evt'],events);
end
C_th=length(idx_high_true);
C_fh=length(idx_high_false);
C_tl=length(idx_low_true);
C_fl=length(idx_low_false);
disp(['Low count:' num2str(C_fl+C_tl) ' Behavior onset rate:' num2str(C_fl/(C_fl+C_tl)*100) '%'])
disp(['High count:' num2str(C_fh+C_th) ' Behavior onset rate:' num2str(C_th/(C_fh+C_th)*100) '%'])