function Hd = BPF_20K_1_4_DF_float_designer
%BPF_20K_1_4_DF_FLOAT_DESIGNER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
% Generated on: 14-Jun-2019 15:11:02

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 1250;  % Sampling Frequency

N   = 2;  % Order
Fc1 = 1;  % First Cutoff Frequency
Fc2 = 4;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% Get the transfer function values.
[b, a] = tf(Hd);

% Convert to a singleton filter.
Hd = dfilt.df2(b, a);
set(Hd, 'Arithmetic', 'single');

% [EOF]
