function Hd = BPF_1250_110_250_DF_float_designer
%BPF_1250_110_250_DF_FLOAT_DESIGNER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
% Generated on: 16-Jun-2019 10:39:49

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 1250;  % Sampling Frequency

N   = 2;    % Order
Fc1 = 110;  % First Cutoff Frequency
Fc2 = 250;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% Get the transfer function values.
[b, a] = tf(Hd);

% Convert to a singleton filter.
Hd = dfilt.df2(b, a);
set(Hd, 'Arithmetic', 'single');

% [EOF]
