function Hd = LPF_20K_1250_DF_float_designer
%LPF_20K_1250_DF_FLOAT_DESIGNER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
% Generated on: 14-Jun-2019 13:06:32

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 20000;  % Sampling Frequency

N   = 4;  % Order
Fc1 = 1;  % First Cutoff Frequency
Fc2 = 4;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');
set(Hd, 'Arithmetic', 'single');

% [EOF]
